export const UPDATE_COLOR_THEME = 'UPDATE_COLOR_THEME';
export const CHANGE_CURRENT_ACCOUNT = 'CHANGE_CURRENT_ACCOUNT';
export const LOGIN_BACKUP_ACCOUNT = 'LOGIN_BACKUP_ACCOUNT';
export const SET_ORIGINAL_ACCOUNT = 'SET_ORIGINAL_ACCOUNT';